# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-04-26 21:10:53 -0700 by alex:
gem "rspec", "~> 3.7"
